apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-svc.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.DNSHost }} 
  labels:
    {{- include "nginx-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-svc.selectorLabels" . | nindent 4 }}
