{{- if .Values.telemetry.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: systest-influxdb
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"

    [http]
      enabled = true
      max-body-size = 0

    # Configure the graphite api
    [[graphite]]
    enabled = true
    bind-address = ":2003" # If not set, is actually set to bind-address.
    database = "jmeter"  # store graphite data in this database
  script.sh: |
    echo "start influxdb"
    influxd &
    sleep 20
    echo "create database"
    influx -host 'systest-influxdb' -port '8086' -execute 'CREATE DATABASE jmeter'
{{- end }}
