{{- if .Values.jmeter.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: influxdb-jmeter
data:
  load_test: |
    #!/bin/bash
    #Script created to invoke jmeter test script with the slaves 
    if [ -n "$5" ]
    then
    echo "JMeter with distributed mode"
    /jmeter/apache-jmeter-5.0/bin/jmeter -n -t $1 -G$2 $3 $4 -Dserver.rmi.ssl.disable=true -Dhttpclient.reset_state_on_thread_group_iteration=false  -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'` 2>&1 | tee jm_summary.log
    else
    echo "JMeter with single mode"
    /jmeter/apache-jmeter-5.0/bin/jmeter -n -t $1 -q $2 $3 $4 -Dserver.rmi.ssl.disable=true -Dhttpclient.reset_state_on_thread_group_iteration=false 2>&1 | tee jm_summary.log
    fi
{{- end }}
